### ISSUE TITLE
Proof of knowledge revealed message structure

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#10]
Related to #2 

Currently the implementations of a BBS proof of knowledge signature includes the encoding of a binary structure at the start of the proof which captures which of the messages being verified and how they correspond to the original ordering of the message set signed. Currently this structure takes the form of a bit array.

For example assume the following set of messages were originally signed

```
[
  "message1"
  "message2",
  "message3",
  "message4",
  "message5"
]
```

And a proof revealing only the 1st 4th and 5th message was generated, meaning the revealed messages supplied during the verify proof operation would appear in the following order

```
[
  "message1",
  "message4",
  "message5"
]
```

The resulting bit array in the proof would take the following form

```
+-----------------------------+-----------------------------+---------------------------------+
| Total messages length (16bit)| Revealed messages bit array |..... remaining proof structure |
+-----------------------------+-----------------------------+---------------------------------+

+-----------+--------------+-----------------------------------+
| 5 (integer) | 1 | 0 | 0 | 1 | 1  | ..... remaining proof structure |
+-----------+--------------+-----------------------------------+
```

However, this mechanism of expression does limit options around the data canonicalisation algorithm that is used on top of the cryptographic scheme. Namely it does not support a re-ordering of the revealed messages away from the order in which they were originally signed. To accomodate this we could instead elect to change the expression of this aspect of the proof from a bit array to a byte/multi-byte array, where instead the array contents is a set of un-signer integers (16bit each) where each integer corresponds to the index the message occupied in the original ordering of the signed message set

For example assume the following set of messages were originally signed

```
[
  "message1",
  "message2",
  "message3",
  "message4",
  "message5"
]
```

And a proof revealing only the 1st 4th and 5th message was generated, **BUT** the messages in the resulting proof are re-ordered so that they present as 4, 5, 1 

```
[
  "message4",
  "message5",
  "message1"
]
```

The resulting bit array in the proof would take the following form

```
+-----------------------------+----------------------------------------+-------------------------------+----------------+
| Total messages length (16bit)| Revealed messages array length (16bit) | Revealed messages byte array | remaining proof |
+-----------------------------+----------------------------------------+-------------------------------+----------------+

+--+--+--------+------------------------------+
| 5  | 3 | 4 | 5 | 1 | ..... remaining proof structure |
+--+--+--------+------------------------------+
```

The tradeoff here is that the overhead of this structure is more than in the simpler case with the bit array.

**NOTE** It is probably also worth considering a more standard structured binary format like CBOR rather than a custom structure

**Comment by swcurran** [comment]
Could someone (perhaps @tplooker or @brianorwhatever?) provide an example (the simplest possible) of a JSON-LD VC that cannot be verified using BBS+, annotating it with how the problem manifests? I'm trying to understand the scope of the issue, and especially, the scope in real world use cases.  Is it anytime that nesting is used, or is it a certain pattern of nesting?  How can a non-JSON-LD person understand the impact?

Thanks!

**Comment by brianorwhatever** [comment]
@swcurran I would take a look at @tplooker comment here https://github.com/mattrglobal/jsonld-signatures-bbs/issues/158#issuecomment-945238151 for the most succint description of the problem. My impression is that it is basically going to happen whenever there is nested objects (unsure how many will trigger it) within the `credentialSubject` that don't have an `id` attribute

**Comment by swcurran** [comment]
It's helpful but not an example of the JSON-LD that triggers the issue. However, [your comment in that same issue](https://github.com/mattrglobal/jsonld-signatures-bbs/issues/158#issue-1005912071) has an example.

As I understand @tplooker's explanation that [you reference](https://github.com/mattrglobal/jsonld-signatures-bbs/issues/158#issuecomment-945238151), the issue manifests in your credential by the existence of the `recipient` and `vaccine` items with no `id` below them.  Presumably, if you had just one item, or all (or all but one) had an `id`, life would be good. And presumably, anytime there is more than one such item anywhere in the JSON will trigger the problem.

That's going to be pretty rough for anyone that wants to use an existing structure as a VC.

**Comment by BasileiosKal** [comment]
@swcurran The problem is related to, but not directly caused, by the serialization algorithm (i.e., URDNA). The problem in the example is caused by the way the Holder communicated the indexes of the revealed messages to the Verifier, because it does not account for the fact that the messages received by the Verifier may not be in the same order that the Holder has them (because of URDNA).

As an example, let’s say that the Holder has messages `m1`, `m2` and `m3` and creates a proof disclosing only `m2` and `m3`. What was proposed to let the Verifier know what messages are disclosed, is that the Holder will also send the bit array `011` indicating that they have 3 messages and that they disclosed the 2nd and the 3rd one. However, if the Verifier gets the messages as `[m3, m2]` (correct messages, wrong order) they will use `m3` like it was the 2nd Holder’s message and `m2` like it was the third. That miss-match will make the verification fail. 

The solution however is not to put `id's` to every nested object in the VC (although that could also work). The simple solution is to communicate the indexes of the revealed messages in a way that will account for the case above. One way to do that is instead of the Holder sending the bit array `011` to send the integers list `[3, 2]` which solves that problem.

**Comment by swcurran** [comment]
Thanks.  Agree that what you state is the "simple solution", but in reality that means agreeing on the exact simple solution, publishing it as a new signature scheme, updating libraries and then updating the existing applications that use those libraries so that arbitrary JSON-LD can be used. That would suggest a long delay in being able to use of BBS+ credentials for general use cases.  Thus, I agree that adding in IDs is not the correct solution, it is a practical hack that will work for the existing scheme.

I noticed, for example, that in publishing the BBS+ version of the mDL schema, that approach was used throughout.

**Comment by brianorwhatever** [comment]
do you have a link to the bbs+ mdl schema @swcurran? sounds interesting!

**Comment by swcurran** [comment]
You can follow the chain to see the approach.  Start here: https://digitalbazaar.github.io/vdl-test-suite/ (Manu posted about this in the W3C CCG).  From the examples, the context for a "vDL" is https://w3id.org/vdl/v1, which resolves to a chunk of JSON that has just has an id for each attribute in the form of:

``` jsonc
       ...
        "family_name": {
          "@id": "https://w3id.org/vdl#family_name"
        },
        "given_name": {
          "@id": "https://w3id.org/vdl#given_name"
        },
        "birth_date": {
          "@id": "https://w3id.org/vdl#birth_date"
        },
        ...
```

I don't know a lot about JSON-LD and perhaps those @id's per attribute are normal.  But I would image they don't contribute much to the semantic understanding (human or machine) of the attributes -- but they do provide an ID.

**Comment by brianorwhatever** [comment]
Cool, thanks for the link. I'm also not a JSON-LD expert but I believe an `@id` is more about what the node is semantically vs an identifier (`id`) for the node which is the issue in this instance. See this example https://www.w3.org/TR/json-ld/#example-4-context-for-the-sample-document-in-the-previous-section

There's also the `"@type": "@id"` line which is often seen in contexts and I don't totally understand..

**Comment by tmarkovski** [comment]
What are the consequences if the signature specification didn't include any revealed message indexes or how they're encoded, and surrendered that responsibility to higher level application suites, like Linked Data and Jose processors. This neither adds nor removes any (more) leaks from the signature format, it's just makes it less opinionated about attaching information to the signature that isn't signed over anyway. This means each application will have to define how to handle index information and not be constrained by the signature format.

**Comment by dlongley** [comment]
+1 to making the low-level signature specification (RFC dealing with the crypto specifically) not be opinionated about message indexes or how the data is encoded but instead just receive appropriately atomized / ordered data for signing. The next layer up (e.g., Data Integrity BBS+ Signature spec / JWP spec) can define how to consume / transform / canonize / order / atomize / etc. the data that is to be passed to the crypto layer.

**Comment by tplooker** [comment]
Thanks @tmarkovski @dlongley for adding to the conversation I agree with much of the sentiment shared. In an effort to clarify further, listed below are the most relevant hard requirements BBS Signatures as a crypto scheme has that is influential in designing the contract/interface and related data structures for a derived BBS proof.

- When verifying a derived BBS proof, the verifying party must know the total number of messages that were originally signed when the signature was created.
- When verifying a derived BBS proof, for any revealed messages (messages that the holder or prover wishes to prove were signed by an issuer), the verifying party must know the placement each revealed message occupied in the original set of messages that were signed.

From my understanding of the opinions shared in this issue and also via DIF slack, is that most people are supportive of a proposal where the cryptographic layer has no opinion about the message indexes leaving it to upstream technologies (e.g LD-Proof or JWP) to make this definition. This means the derived BBS proof structure defined by this draft will only describe the direct cryptographic information of the proof.

Given that proposal we still need to decide how the contract for verifying a deriveProof should change, for instance the current draft defines

```
result = SpkVerify(spk, PK, (msg[i],...,msg[D]), nonce)
```

where D is the number of revealed messages makes the following invalid assumptions

- spk contains information on the total number of messages originally signed
- spk contains some form of mapping that maps the revealed messages (msg) to their original position in the originally signed message set.

One potential proposal would be to change the contract for verifying a derivedProof to something like

```
result = SpkVerify(spk, PK, revealedMessages, totalSignedMessages, nonce)
```

Where revealed messages is a map of the following structure

```
{
  1: octet_string_msg_1,
  5: octet_string_msg_5,
  9: octet_string_msg_9,
}
```

**Comment by tplooker** [comment]
Another option is to retain the total signed messages as a value encoded in to `spk` to reduce the need to manage it externally, however still handle the ordering of the revealed messages in the way described above

**Comment by tmarkovski** [comment]
Is `PK` already a function of `totalSignedMessages (L)` (via `PK = DpkToPk(DPK, L)` or `PK = SkToPk(Sk, L)`)? If yes, then encoding it doesn't save much work.
I like your proposal with `result = SpkVerify(spk, PK, revealedMessages, totalSignedMessages, nonce)` and using a map to unambiguously describe the message input.

Implementation wise, I think application suites can choose to continue to encode the signature as it is currently, by encoding the total, indexes and proof into a single field, as long as their spec is clear this is the case. That said, we may end up with `signatureValue` in LD proof having different format than signature in JWT, because one chose to encode additional data into the signature. Is this a problem overall?

**Comment by BasileiosKal** [comment]
>  That said, we may end up with signatureValue in LD proof having different format than signature in JWT, because one chose to encode additional data into the signature. Is this a problem overall?

Upon further investigation, the revealed messages re-ordering issue seems to be caused by IDs that are of similar format as the blank node labels IDs. This could have a simple solution (re-sorting after transforming back to blank node labels) that will allow the LD proofs to use a bit array appended to the proof value, as originally proposed [here](https://github.com/w3c-ccg/ldp-bbs2020/issues/22). This can also eliminate the dangers of a correlation because of the re-ordering of the revealed messages.

That been said, IMO the bbs+ spec should remain agnostic to the way the indexes of the revealed messages are encoded. This could lead to the proofValue having different formats between implementations; however, IMO this is not a problem. Higher level specs like JWP and LD-proofs will most likely want to use different formats for the revealed message indexes either way, because of the way they work.

**Comment by tplooker** [comment]
> Is PK already a function of totalSignedMessages (L) (via PK = DpkToPk(DPK, L) or PK = SkToPk(Sk, L))?

Thanks thats a good call out, which reminded me to file #26 given the resolution to that issue I am suggesting does my proposal make more sense? e.g PK would be an ordinary public key (Note - I release this change impacts several other sections in the draft).

> Implementation wise, I think application suites can choose to continue to encode the signature as it is currently, by encoding the total, indexes and proof into a single field, as long as their spec is clear this is the case.

Yes I think the point to clarify is that from this drafts perspective any data structure like a reveal indices array would be left to a higher level draft to define.

> That said, we may end up with signatureValue in LD proof having different format than signature in JWT, because one chose to encode additional data into the signature. Is this a problem overall?

Given they are different digital signature representation formats I expect divergence at some level. So long as the core structure of any signature / proof and public key value remains structually the same upstream then I dont think we can prevent additional data structures being wrapped around them?

**Comment by tplooker** [comment]
> That been said, IMO the bbs+ spec should remain agnostic to the way the indexes of the revealed messages are encoded. This could lead to the proofValue having different formats between implementations; however, IMO this is not a problem. Higher level specs like JWP and LD-proofs will most likely want to use different formats for the revealed message indexes either way, because of the way they work

+1 I think much of the different at these representation layers is really due to different approaches to problems like data canonicalization which should remain entirely opaque to the crypto layer (the concern of this draft)

**Comment by tplooker** [comment]
I think the opinion of the group has evolved sufficiently on this issue to conclude that any higher level serialization rules that accounts for the ordering of the messages required for operations like spkVerify and verify should be left to the application layer, therefore im marking this issue pending close, if others in the WG dis-agree please feel free to comment otherwise it will be closed during the next WG call.
