### ISSUE TITLE
Update KeyValidate operation definition

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#109]
With the changes to how we handle the message generators the procedure as defined in this section doesn't make sense now as they are no longer apart of the public key, therefore this should be updated to reflect that.

**Comment by tplooker** [comment]
We also need to update the syntax of using this operation inside other operations like verify and spkGen which is currently inconsistent.

**Comment by tplooker** [comment]
Also once we have merged #95 I think we need to update so that KeyValidate is called for both the sign and spkGen functions also as the public key will now form part of the DST signed into the signature? @BasileiosKal

**Comment by tplooker** [comment]
[Current language](https://identity.foundation/bbs-signature/draft-bbs-signatures.html#name-validating-public-keys) in the specification hints at this check being performed across all operations, we should clear up this confusion.

**Comment by BasileiosKal** [comment]
It may be best to be careful, but I don't think there is an pressing reason to include keyValidate in sign and spkGen. It's use in verify and spkVerify is so we will not pass elements not in G2 in the pairings which may resolve to unpredicted behavior. The same danger doesn't seem to exist in sign and spkGen though since we just hash the value. 

That said we must update the keyValidate procedure as described by @tplooker as well as clarify it's use.

**Comment by BasileiosKal** [comment]
Thanks for the context. In that vulnerability the issue seems to be that key-validation was skiped in verify. A mallicius prover can just skip key validation either way. If we consider a malicious issuer and an honest prover senario though, then a best strategy could be for the prover to veriy the entire signature (which would also call KeyValidate) instead.

That said, i don't see any practical application in this security model (dishonest issuer, honest prover), so i would sugest removing keyValidate from spkGen and adding a security consideration to cover all the caeses after.
