### ISSUE TITLE
Improve Terminology and Syntax Consistency

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#114]
Related to #25 currently the spec has a mix of casing for operation names, inputs, parameters and outputs this should be made consistent including whether short or more descriptive names are used.

Suggested rules for inputs outputs and parameters 

- use snake case
- use fully qualified names e.g msg -> message PK -> public_key

Suggested rules for function naming

- use snake case e.g SpkGen => spk_gen

**Comment by tplooker** [comment]
I'd also like to clarify that I think the section names should shift to using fully qualified names e.g KeyGen -> Key Generation where the actual function name would be `key_gen`

**Comment by tplooker** [comment]
alternatively if we think names will become to large even with just applying the rule to inputs outputs and parameters, then I'm happy to stick with brief names e.g msg

**Comment by tplooker** [comment]
Raised by @BasileiosKal on the call the proposal to rename SpkGen to ProofGen or something similar because the proof is not just a signature proof of knowledge.

**Comment by BasileiosKal** [comment]
My proposal for a terminology convention is:
1. All EC points to be capital even in their octets representation (i.e., pub_key -> PK)
3. All special points in G1 will be Pi, i = 1, 2, etc. For example, P1 will be the base point of G1, P2 will be the generator for the blind value (H_s in #95) and P3 the generator for the signature domain (H_d in #95). So B will be
```
B = P1 + P2 * s + P3 * domain + H_1 * msg_1 + .... + H_L * msg_L
```
4. All special points in G2 will be Qi, i = 1, 2, ..etc. This means that the base point in G2 will be Q1 and the pub key will be PK = Q1 * SK.
5. All scalars will be lower case (i.e., SK -> sk)
6. Core functions will be pascal case (i.e., proofVerify -> ProofVerify)
7. Helper functions will be snake case. I'm going back and forward on this one since it will give us consistency with many functions we use from the h2c spec, however as @andrewwhitehead pointed it may be better to be internally consistent. So im also fine with making every function pascal case.

**Comment by tplooker** [comment]
Labeling as pending close ahead of WG call on the 4th of july

**Comment by BasileiosKal** [comment]
Updates discussed to WG call:
`Ciphersuite_ID` -> `ciphersuite_id`
`H_s, H_d` -> `Q_1, Q_2`
`MsgGenerators` -> `msgGenerators`

**Comment by tplooker** [comment]
Discussed on 8th august WG call, closing
