### ISSUE TITLE
Reducing hash functions

### ISSUE THREAD

**Issue by andrewwhitehead** [decentralized-identity/bbs-signature#162]
There are several different uses of hash functions within the draft. These generally refer to the `hash` parameter, but some refer to the `xof` parameter, which currently appears independent. For compatibility, every hash function that is used in operations by multiple parties must be referenced in the ciphersuite ID. Because we don't want to list several hash functions here, and because supporting multiple hash functions adds extra dependencies (and implementation cost, platform incompatibilities, potential vulnerabilities) I suggest we try to reduce requirement to a single hash function per ciphersuite. Here are the use current cases I've identified:

- In `hash_to_scalar`: Used to generate various scalars within signature and proof generation. We have a proposal to add an XMD version to support non-XOF hashes. This is the primary use of the hash function.
- Within `KeyGen`: this one doesn't need to be included in the ciphersuite ID as it has no impact on other parties. Maybe the hash function should become an input parameter? If we want to keep this operation.
- In generator creation:
    - The current method uses an XOF to generate a stream of bytes which is then fed into a hash-to-curve implementation. If we want to support non-XOF hash functions then we might need to define an alternative method (like the one in the old draft).
    - The chosen hash-to-curve suite should be required to use the same hash and a compatible `expand_message` method (XOF or XMD). It must also use `hash_to_curve` not `encode_to_curve` in order to guarantee a uniform distribution, ie. the suite identifier must end with 'RO'.
- Hashing message inputs:
    This one seems a little problematic. It is essential to the security of the signature scheme that all parties understand the encoding used to create the message scalars. Some implementations are going to need type-aware conversion of input values to scalars, which seems beyond the scope of this spec as it implies a dependency on a schema to define the value types. We could completely avoid standardizing message-to-scalar conversion and only use predefined scalars in the test cases. On the other hand, I also believe we need to support the base-level use case of simply signing one or more octet strings, in which case 'MapMessageToScalarAsHash' is sufficient. (In this case, do we want to require that the hash used to convert input messages is the same as the hash used within the other operations?)
    In order to support both the typed-values message encoding use case and the simple hash-and-sign use case, perhaps we could add a simple parameter to the ciphersuite ID to distinguish between the two. We could add an ENC_TAG with two values: RAW (treat all input messages as octet strings), and SCHEMA (validate message inputs according to the associated schema, and apply its rules for converting into message scalars). When the ENC_TAG is SCHEMA, then a schema identifier would need to be included in the header value or somehow implied at the application level – I don't think we need to formalize this beyond adding a security guideline.

**Comment by andrewwhitehead** [comment]
TBH I think the current effort to support non-XOF hash functions is impeding progress, and we should revisit that after a first draft if at all.

**Comment by andrewwhitehead** [comment]
Upon consideration, we don't want to use this ENC_TAG within the ciphersuite ID, as then we'd need to define twice as many ciphersuites. Perhaps this can just be left to the application level?

**Comment by BasileiosKal** [comment]
Agreed with the direction! IMO a suite should define that whatever hash is used for h2c will be used for everything else ass well (mainly hash_to_scalar, which is also used by `MapMessageToScalarAsHash`). That way the H2C_ID is enough to characterize the suite. 

As far as usefulness of the non-xof hash_to_scalar I'm (obviously) of the opinion that is needed. The reason is that a lot of times, only supporting an xof has caused issues in the impenetrability of the scheme, for example, when trying to use libs that don't support shake256 (but they do support h2c with sha256 like [blst](https://github.com/supranational/blst) or [noble-bls12-381](https://github.com/paulmillr/noble-bls12-381)). Personally, I would like to push a first draft with two ciphersuites, one using shake256 and one using sha256. That way, it will be very easy to implement bbs+ with bls12-381 libs, that are targeted to bls-sigs (that are most of them AFAIK).

To further support the above, I'm also worried that developers will use a lib like the above, with a sha256 based h2c implementation, and just use shake256 for everything else, essentially implementing a wrong suite (which can be dangerous).

Of-course always more than happy in keep discussing this. If the group feels that the _xmd version of hash_to_scalar is not worth wile right now I'm more than happy to close PR #151.

**Comment by andrewwhitehead** [comment]
Yes, I think the key is that a 'raw' BBS signature is unlikely to be encountered in the wild – it will be wrapped in a JWS, or a VC, or some other container which defines the interpretation (including the ciphersuite) and hopefully protects that associated data using the header. And of course on the verifier side they will often only see a proof of a signature. I do think we want to avoid the perception that input messages are always hashed.

> Personally, I would like to push a first draft with two ciphersuites, one using shake256 and one using sha256. That way, it will be very easy to implement bbs+ with bls12-381 libs, that are targeted to bls-sigs (that are most of them AFAIK).

Well.. it will be easy to implement the sha256 version, but that won't help compatibility with libraries that use shake256. Maybe we should be focusing on adding XOF support to those libraries instead of complicating the spec, or defining an XOF-like primitive based on HDKF.

**Comment by BasileiosKal** [comment]
That's true! And definitely something to consider! The two ciphersuites will not be compatible with each other either way though?? (when it comes to the challenge hash for example). So IMO it's fine to have two different suites that target two different groups of implementations. Since the spec is pretty well suited for use with an xof already (which is very much encouraged), I don't see why also supporting a fixed-output-length hash would do more harm than good (when it comes to the compatibility with shake256 supporting libs)?? 

Of-course, raising the complexity of the spec is something that i also want to avoid as much as possible. However, in this case, i think its worth it since,
1. IMO it's for a good reason (I do believe that adding this support on the spec will allow use of a much wider range of already established implementation + i think it's much easier than trying to add xof support to those libs)
2. I don't think complexity will be raised that much. It will be at most 2 more operations (`hash_to_scalar_xmd` and maybe a `compute_generators_xmd`. although i don't think the last one is even needed).

When it comes to HKDF I'm not at all opposed to it. However, it is less efficient. We could also use hash_to_field, although that too is less efficient. In any case I'm fine with the approaches, as long as we have something so we will not make implementing a suite using sha2 next to impossible (as it kinda is right now IMO). In general, currently the spec does fill to me like we try to "force" people in an xof, which I don't think it's wise (IMO many will choose to just not be compatible with the spec than implementing shake256, if they get the chance).

Of-course i could be convinced otherwise. Lets discuss this more!!

(Also i do agree that each suite should be able to be used with only 1 hash and I do think it will be possible with the direction the spec is currently going)

**Comment by andrewwhitehead** [comment]
It looks like there are two slightly odd cases, KeyGen and MapMessageToScalarAsHash, which are inheriting the suite's hash parameters but don't necessarily need to because they aren't directly involved in signature generation or verification. Favouring simplicity, though, I think it's fine to only define these in terms of the suite's hash parameters. In both cases alternatives can be used instead, so we are only providing a useful default implementation.

**Comment by BasileiosKal** [comment]
That's a great point! I haven't considered those cases. I do agree that those are just suggestions that cater the more "simple" use cases so it's fine to define everything based on 1 hash??

As a side note. I do start to believe that we overthinking this. Similar considerations could apply to [bls-signatures](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-04#section-2.9) (for the ''Aggregate" scheme) however they just leave everything to the upper layer, and it makes for a readable spec (they don't even worry about PK and message correspondence and ordering in [AggregateVerify](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-04#section-2.9), which has been a big discussion here).

Personally i would leave `KeyGen` as it is with a note that it is optional but if used it must use whatever hash is defined by the suite. Same for `MapMessageToScalarAsHash`. As you [pointed out](https://github.com/decentralized-identity/bbs-signature/issues/162#issuecomment-1144134405), bbs+ will be warped to containers that will specify the message encoding. To avoid the perception that each message is hashed, we could move the `MapMessageToScalarAsHash` to the appendix, have a discussion around message encoding in the main part and only point to this operation as an example.

**Comment by BasileiosKal** [comment]
In any case i think we are mostly in agreement here?? Maybe we should start with the xof vs hash discussion on the next call, as i think it's the main issue holding back some progress. Deciding on a direction would be very helpful.

Just to try and clarify the options:
- **Option 1**: Define everything on the basis of an xof only. This means `hash_to_scalar`, `hash_to_curve` + `createGenerators` and `MapMessageToScalarAsHash`.
    - Advantages: fewer and simpler operations i.e., no need for [hash_to_scalar_xmd](https://github.com/decentralized-identity/bbs-signature/pull/151) or a more complicated `createGenerators` procedure (like the proposals [here](https://github.com/decentralized-identity/bbs-signature/pull/161#discussion_r887355556))
    - Disadvantages (-**IMO**-): making it hard to define a sha2 based suite, and as a result, to use certain libraries like [blst](https://github.com/supranational/blst) and [noble-bls12-381](https://github.com/paulmillr/noble-bls12-381).
- **Option 2**: Add support for fixed-output-length hash functions.
    - Advantages (-**IMO**-): Ability to easier use a wider range of bls-sigs targeted implementations. Ease of defining sha2 based suites, that can give rise to more use cases (like emending systems or blockchain based ones).
    - Disadvantages: (As described above) higher spec complexity + more time and effort required to add that support, at a time that we maybe should be focusing on other things.

Please let me know @andrewwhitehead if the above is not accurate or if i missed something. I'm also very keen to hear others opinion around this!

**Comment by andrewwhitehead** [comment]
Yes I think that's a good summary, and we should definitely hash it out (lol) on the next call.

**Comment by christianpaquin** [comment]
One drawback of the xof-only option is that the [hash to curve spec](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-14#appendix-J.10) only defines SHA256 test vectors for BLS. If we adopt the xof method, we'd need to specify these test vectors as well. The implementation point noted above is also important: the lack of library support for this option complicates the implementation. The level of expertise required to implement the low-level pairing primitives vs. the BBS app layer are vastly different; it blocked my own progress on my javascript ref implementation using the noble library.

**Comment by BasileiosKal** [comment]
@andrewwhitehead can we close this now after the merge of #177 and #151??
