### ISSUE TITLE
More flexible default generators

### ISSUE THREAD

**Issue by andrewwhitehead** [decentralized-identity/bbs-signature#19]
At the moment, the default generators are defined using roughly the formula `hash-to-curve(PK || index || count)`, meaning that the generators are dependent on both the public key of the issuer and the number of signed messages.

There is also discussion of wanting to use a set of predetermined random generators instead of the default generators, in which case the generators would be independent of both the public key and the number of messages in the signature.

In the interest of aligning these approaches somewhat, I think it's worth considering removing the message count from the hash input, so that the default generators depend only on the public key of the issuer. This could have positive effects on performance given that all the generators could be cached up to a maximum number of signed messages.

This change might also be relevant in the case of JSON-LD credentials. In order to commit to one or more hidden messages (to implement holder binding for instance) a holder would need to have the relevant message generators. But the total number of messages is often not known at this point in the credential exchange protocol, because the JSON-LD credential itself (including the proof block?) would need to be generated and normalized first. If the generators were independent of the number of messages and the hidden messages were among the first messages (not added to the end) then this would be made possible.

**Comment by mikelodder7** [comment]
I'm fine if we want a different formula. As long as the inputs have sufficient entropy.

**Comment by tplooker** [comment]
Another option is for the message generators to be pre generated and shared globally rather than being issuer specific like the proposal above. 

Discussed on 10th Jan WG call, resolved to add a section to the spec that speaks about message generator creation which will take a seed and output a list of message generators

**Comment by tplooker** [comment]
@andrewwhitehead will provide a PR that defines ^ process

**Comment by andrewwhitehead** [comment]
There was some discussion on the call around a DST for the generators. This is an extra parameter to hash-to-curve (besides the seed and message index used as input) which would separate generators used for different signing algorithms. Currently the draft specifies `BLS12381G1_XMD:BLAKE2B_SSWU_RO_BBS+_SIGNATURES:1_0_0`. I think for the next draft it might be something like `BLS12381G1_XOF:SHAKE256_SSWU_RO_BBS+_SIGNATURES:2022`. This implies that the chosen seed value should not include such information, and might be something trivial like the encoding of the words `message generators` in the common case.

**Comment by mikelodder7** [comment]
Message generators must NOT be shared globally. They must be unique per public key for the protocol to be secure

**Comment by mikelodder7** [comment]
My proposal is to use Shake256(“BBS_Domain_Generators” || pk || count) to seed  the Xof then draw 64 bytes for each generator  and call hash2curve on the 64 bytes. That runs must faster than the current method in Ursa and is more secure

**Comment by tplooker** [comment]
@mikelodder7 can you elaborate on the specific security concern here when using global message generators, this model would be similar to some usages of U-Prove, perhaps you could elaborate @christianpaquin

**Comment by mikelodder7** [comment]
U Prove is a bad comparison. See  https://eprint.iacr.org/2012/298.pdf from Anna Lysyanskaya which says `UProve is not provably secure! No proof of security has been given under any reasonable assumption; and in fact, recently, Baldimtsi and Lysyanskaya [3] showed that all known approaches for proving security in the random oracle model will fail for the Brands blind signature scheme on which UProve is based, under essentially any assumption.`

As for a universal setup for BBS+, I have not seen any formal security proofs for one way or the other. Let me review the literature to see what I can find.

**Comment by christianpaquin** [comment]
As long as `h0` is different, the other `h_i` could be shared, no? This is not a U-Prove specific construct, this should work for messages built using a Pedersen commitment constructions. BBS+ and, e.g., U-Prove are not equivalent, sure, but these types of protocols have been long studied in the literature, even if there is no formal security proof (ECDSA doesn't have a security proof either...)

**Comment by christianpaquin** [comment]
To clarify: we indeed need to make sure that the spec remains secure. BBS+ has a security proof, which _is_ a great benefit, so we should be careful to keep that. Camenisch-Drijvers-Lehmann's paper use random generators. Maybe they absolutely need this to prove the security. Maybe the shared generator approach is also secure (in practice), but can't be proven. We'd be stuck with a design choice of provable security vs. efficiency.

**Comment by mikelodder7** [comment]
We’ll ECDSA does have security proofs by they’re wierd.

Suppose we have universal generators h_i, if I commit to a value using that it will be the same for all signatures. Think same encryption same key same message problem. This is why AES and CHACHA use nonces to remove this problem. Same key, same message, different nonce means the attacker can’t tell if the same message was encrypted with the same key. Nonce reuse attacks do happen.

You raise an interesting point to just have a random h_0. I’ll think about that some more. In general though I still think the generators need to be context specific or domain separated

**Comment by christianpaquin** [comment]
It'd be worthwhile to have various academic experts review the v1 spec (when ready), wherever we land.

**Comment by tplooker** [comment]
> It'd be worthwhile to have various academic experts review the v1 spec (when ready), wherever we land.

+1 we will definitely seek broader review when appropriate.

 > To clarify: we indeed need to make sure that the spec remains secure. BBS+ has a security proof, which is a great benefit, so we should be careful to keep that. Camenisch-Drijvers-Lehmann's paper use random generators. Maybe they absolutely need this to prove the security. Maybe the shared generator approach is also secure (in practice), but can't be proven. We'd be stuck with a design choice of provable security vs. efficiency.
 
 This is IMO is core to conversation here, is the random nature in which the generators are create0d in this paper, core to the security proof, if not is there a provable security benefit in these generators instead being issuer specific (e.g derived from the issuers public key) otherwise the simplest possible implementation would be for them to be global public parameters.

**Comment by tplooker** [comment]
> In general though I still think the generators need to be context specific or domain separated

@mikelodder7 is there a security basis you can point to for needing this? Anyway we could clarify with the authors of the Camenisch-Drijvers-Lehmann's paper whether the generators being generated randomly contributes to the security?

**Comment by BasileiosKal** [comment]
> Suppose we have universal generators h_i, if I commit to a value using that it will be the same for all signatures. Think same encryption same key same message problem. 

The bbs+ proof is also randomized even without a nonce (through r1, r2 etc.). Furthermore, the proof that it is zero knowledge does not make assumptions about the generators. The fact that it is zero-knowledge I think can ease those concerns. (not to say that it is not important for the generators to be sufficiently randomized)

In literature, it is true that Camenisch, Drijvers and Lehmann have hi as random elements and part of the Issuer’s key but Man Ho Au, Susilo and Yi Mu refer to them as “public common parameters” and calculate them in a issuer independent way. In the end, if the generators are sufficiently randomized through a secure hash-function I don't see why any of the proofs will not be holding. But I also agree that care must be taken and contacting the authors seems a greet idea.

**Comment by tplooker** [comment]
> In the end, if the generators are sufficiently randomized through a secure hash-function I don't see why any of the proofs will not be holding

@BasileiosKal can you clarify, do you mean so long as the message generators were generated in a sufficiently random manner then they are safe to be re-used across multiple signatures even from different issuers? Or that they must be universally random?

**Comment by BasileiosKal** [comment]
> @BasileiosKal can you clarify, do you mean so long as the message generators were generated in a sufficiently random manner then they are safe to be re-used across multiple signatures even from different issuers? Or that they must be universally random?

Yes my argument is that I think it is safe to reuse generators, as long as they where originally created to be sufficiently random.

**Comment by mikelodder7** [comment]
I’m not as worried about the proofs as I am the signing. The other proposal from this group is to make signing deterministic which might also impact this.

**Comment by tplooker** [comment]
> I’m not as worried about the proofs as I am the signing

Is there a more specific security concern you could elaborate on here?

> The other proposal from this group is to make signing deterministic which might also impact this.

Anyway we can improve the understanding of the implications of this? For example does the current proposal for deterministic signatures for BBS mean that using global message generators across signatures is not possible?

**Comment by tplooker** [comment]
@mikelodder7 any follow up here about a specific security concern?

**Comment by mikelodder7** [comment]
> > I’m not as worried about the proofs as I am the signing
> 
> Is there a more specific security concern you could elaborate on here?


using the same generators with signatures could potentially leak the messages signed since the commitments will always be the same. Researching to see if this is as bad as I think it might be or not

> 
> > The other proposal from this group is to make signing deterministic which might also impact this.
> 
> Anyway we can improve the understanding of the implications of this? For example does the current proposal for deterministic signatures for BBS mean that using global message generators across signatures is not possible?

No we should be able to but it does mean signatures are distinct and unique which cryptographically isn’t a problem but could be correlation risk.

**Comment by andrewwhitehead** [comment]
> using the same generators with signatures could potentially leak the messages signed since the commitments will always be the same.

I'm a bit confused, was it suggested to make the commitments deterministic as well?

**Comment by BasileiosKal** [comment]
It’s true that random and fixed generators are not always equivalent (as shown by this https://eprint.iacr.org/2019/202.pdf paper). However, a takeaway from the paper is that that CDH is just as strong (or even stronger) in cases where a fixed, instead of a random generator, is used. The same result is proven for DL. Wouldn’t that mean that if the sk is sufficiently randomized, the signature will be Indistinguishable from any other element in the group??

Another detail is that if we decide to use fixed generators, we should specify that the secret key should not have any dependency to that generator, to avoid problems like in the case of the strong power DDH mentioned in the same paper.

> No we should be able to but it does mean signatures are distinct and unique which cryptographically isn’t a problem but could be correlation risk.

Wouldn't that be the case even if the generators are not fixed?? If e and s are random, the signatures will be unique. IMO we should add a section to the Security Considerations, saying that the signature should be kept secret to avoid correlation.

**Comment by BasileiosKal** [comment]
After thinking more about this there may be a potential problem. Pairings make DDH in G1 easy, both in the fixed and in the random generator setting. Furthermore, I think there is a way, using exactly this fact, for an adversary to decide if 2 signatures are on the same messages `mod q`, if a fixed generator is used. 

If `((P1 + h0*s1 + h[1]*msg1)*(1/(e1+SK)), e1, s1)` and `((P1 + h0*s2 + h[1]*msg2)*(1/(e2+SK)), e2, s2)` are two different signatures on `msg1` and `msg2` respectively (same generators and key, different `e` and `s` values) then the adversary could compute

```
I1 = e((P1 + h0*s1 + h[1]*msg1)*(1/(e1+SK)), w+P2*e1) * e(-P1 - h0*s1, P2) = 
    = e(P1 + h0*s1 + h[1]*msg, P2) * e(-P1 - h0*s1, P2) => I1 = e(h[1]*msg1. P2)

I2 = e((P1 + h0*s2 + h[1]*msg)*(1/(e2+SK)), w+P2*e2) * e(-P1 - h0*s2, P2) = 
    = e(P1 + h0*s2 + h[1]*msg, P2) * e(-g0 - h0*s2, P2) => I2 = e(h[1]*msg2. P2)
```

As a result, if I'm not mistaken, the adversary could check if `I1 = I2` to decide if `msg1 = msg2 mod q`, which can correlate the two signatures. Note that the above method only works if there is only 1 message been signed by each signature.

However, we can also prove that an adversary can not extract the message from the signature since such an adversary could be used to solve DL in G1; If the adversary `A` on input a bbs+ signature on the message `m` returns that message, we could just query `A` with `((g0 + h0*s + a)*(1/(e+x)), e, s)` where `a = h[1]*c` is the DL problem we trying to solve. Notice that the query is a valid bbs+ signature on `c` meaning that we will get from `A` the DL of `a` on the basis of `h[1]`, i.e., `c`.

For that reason, and the fact that even if we used random generators, there is no proof (currently) that two signatures on the same message couldn't be correlated (for example, if the same method as in the security proof of Lemma 1, in [this](https://eprint.iacr.org/2016/663.pdf) paper, is used to create random generators, the same method as above could be used to decide if `msg1 = msg2 mod q`), IMO the added complexity of using different random generators for each signature is not worth it. In most applications, the signatures will be kept private to avoid correlation either way, while if someone wants to actually use the signature, they will also disclose the signed messages.

**Comment by tplooker** [comment]
@mikelodder7 ^

**Comment by tplooker** [comment]
@BasileiosKal if I understand your analysis correctly, if we do migrate to a construction of a BBS+ signature that is deterministic in nature on purpose due to the benefits it brings, then the ability for a possessor of two BBS signatures issued by the same issuer to know that the same set of messages were signed would become apparent anyway?

In general I agree with the thinking that correlation via the signature value is not a concern, this is present with most digital signature schemes anyway (esp those that are deterministic in nature like EdDSA or the deterministic construction for ECDSA). The added anti-correlation mechanisms of BBS+ come via the derived proofs, we should add a section in the privacy considerations that describes this nuance

**Comment by BasileiosKal** [comment]
> if we do migrate to a construction of a BBS+ signature that is deterministic in nature on purpose due to the benefits it brings, then the ability for a possessor of two BBS signatures issued by the same issuer to know that the same set of messages were signed would become apparent anyway?

Yes exactly. IMO this will not have any practical significance, especially since the message itself and the SK will be secure against an attacker. An addition to the security considerations section should suffice.

**Comment by mikelodder7** [comment]
Overall, I believe this is a good direction. But, I'd like to do formal security proof that default generators in a universal setup are secure. Also, the generator procedure should be able to be done via computation like domain -> shake256 -> hash2curve(index, okm, dst) -> G

**Comment by andrewwhitehead** [comment]
> If `((P1 + h0*s1 + h[1]*msg1)*(1/(e1+SK)), e1, s1)` and `((P1 + h0*s2 + h[1]*msg2)*(1/(e2+SK)), e2, s2)` are two different signatures on `msg1` and `msg2` respectively (same generators and key, different `e` and `s` values) then the adversary could compute
> 
> ```
> I1 = e((P1 + h0*s1 + h[1]*msg1)*(1/(e1+SK)), w+P2*e1) * e(-P1 - h0*s1, P2) = 
>     = e(P1 + h0*s1 + h[1]*msg1, P2) * e(-P1 - h0*s1, P2) => I1 = e(h[1]*msg1. P2)
> 
> I2 = e((P1 + h0*s2 + h[1]*msg2)*(1/(e2+SK)), w+P2*e2) * e(-P1 - h0*s2, P2) = 
>     = e(P1 + h0*s2 + h[1]*msg2, P2) * e(-g0 - h0*s2, P2) => I2 = e(h[1]*msg2. P2)
> ```
> 
> As a result, if I'm not mistaken, the adversary could check if `I1 = I2` to decide if `msg1 = msg2 mod q`, which can correlate the two signatures. Note that the above method only works if there is only 1 message been signed by each signature.

As noted, this wouldn't really matter for signatures from a single issuer if deterministic signatures are adopted, however... when the same generators are shared, then it also works for signatures across multiple issuers, regardless of having deterministic signatures.

That said, I've been generally assuming that when the signature value itself is revealed, then all the messages are also expected to be revealed. That would be worth documenting if it is the case.

**Comment by BasileiosKal** [comment]
> But, I'd like to do formal security proof that default generators in a universal setup are secure

+1. What security properties do we need to prove in the universal default generators setup?? Both the SK and -if my computations where not wrong- the message, are provably secure. On the other hand, the signatures could be correlated. What other security properties should we turn our attention to?

**Comment by BasileiosKal** [comment]
> As noted, this wouldn't really matter for signatures from a single issuer if deterministic signatures are adopted, however... when the same generators are shared, then it also works for signatures across multiple issuers, regardless of having deterministic signatures.

That’s a very interesting point. Maybe we should define P2 as issuer specific to avoid this problem (cross-issuer correlation of signatures on the same message)?? Although I do agree that it still does not seem to have enough practical significance to validate the added complexity. Adding to the documentation seems necessary though.

**Comment by mikelodder7** [comment]
> +1. What security properties do we need to prove in the universal default generators setup?? Both the SK and -if my computations where not wrong- the message, are provably secure. On the other hand, the signatures could be correlated. What other security properties should we turn our attention to?

First, it should be secure in the scenario where multiple issuers are reusing the generators and it shouldn't be possible to know if the same message is signed at the same position. Second, an attacker should not be able to trick a signer by copying the commitments to another signer. I'll try to think of more properties as we go along. The second solution is already partially accounted for by using a blind signature proof of knowledge of committed values. I'm worried about the first scenario for both signing and proving.

**Comment by tplooker** [comment]
> First, it should be secure in the scenario where multiple issuers are reusing the generators and it shouldn't be possible to know if the same message is signed at the same position.

@mikelodder7 can you elaborate on this more, do you mean by a party that have two signatures from two issuers or two proofs? Because I agree if it is the latter but if it is the former, what is the attack vector?

> Second, an attacker should not be able to trick a signer by copying the commitments to another signer

Im unsure how universal/global generators would facilitate this deceit?

**Comment by andrewwhitehead** [comment]
At this point generator creation has been mostly reduced to the choice of a seed value. Closing as there are no currently proposed changes.
