### ISSUE TITLE
Serialize returns INVALID

### ISSUE THREAD

**Issue by rolfhaenni** [decentralized-identity/bbs-signature#295]
The serialize() algorithm in Section 4.2.4.1 does not include the case where an element of the input array is a string.
However, exactly this happens in Lines 4 of coreSign(), where the string comm passed as input value to serialize(). Therefore, currently serialize() would return the value INVALID. Besides, the commitment is missing in Line 2 of CoreVerify().

**Comment by BasileiosKal** [comment]
This is absolutely correct! Resolved by [PR 297](https://github.com/decentralized-identity/bbs-signature/pull/297). The `commitment` value is removed since it did not seem to serve much its original purpose, which was to support Blind BBS Signatures, now [its own document](https://github.com/decentralized-identity/bbs-signature/issues/292).

Thank you for raising the issue! Will mark it as resolved and close it if there are no objections.
