### ISSUE TITLE
Ensure SpkGen algorithm is still consistent with academic literature

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#69]
Opening this to track the ongoing work happening in the background after the merging of #62, @BasileiosKal and @mikelodder7 will co-ordinate on this and once complete we can close this issue

**Comment by BasileiosKal** [comment]
Just to track some issues. All of those may become mute from issue #70.

1. After talking with Mike i understood that the problem was not that the equations between the spkGen and spkVerify are not consistent but that they are not consistent with the paper, especially the ones going into the SPK. Specifically, the first equation proven by the SPK in the spec now is `Abar - D = - A' * e - H0 *r2` while the same equation in the paper is `Abar - D = - A' * e + H0 *r2`. The second equation is the same in both cases. From my calculations, there is an extractor for those equations, however its quite different from the one used in the paper, which means we must describe it in the spec. IMO it would be better to change `r2^ = r2~ + c * r2` to  `r2^ = r2~ - c * r2` so at least the equations going into the SPK will be the same as in the paper, meaning that we don't have to describe a new extractor in the spec. Changing the formulas is fine but i would prefer equivalent equations to go into the SPK so we don't have to describe a new extractor, especially since it doesn't seem to give to much of an efficiency advantage (it's only calculating one more negative).

2. Just to track another issue here, Mike mentioned that the `m^_i` in `C2` in spkVerify may need to go with a "-", although looking at it now it seems consistent?? because of the `-r3~` and `-r3^` multiplied with `D`? I may be missing something.

**Comment by tplooker** [comment]
Closing in favour of #79 which documents a broader set of considerations.
