### ISSUE TITLE
Parameterise the bytes drawn from the XOF so they are defined by the cipher suite

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#94]
Throughout the operations defined by the spec there are numerous calls to the XOF where a certain number of bytes are read, via the .read() function. How many bytes are read is dependent on several decisions at the cipher suite level (e.g the curve used) hence the current "magic numbers" like 64 being used in these operations needs to be parameterised in the cipher suite definition.

**Comment by andrewwhitehead** [comment]
This could be added as a simple ciphersuite parameter (a constant), or it could be defined generically.

The BLS signature draft uses `ceil((3 * ceil(log2(r))) / 16)` bytes (48 bytes for BLS12-381), while the draft currently uses 64 bytes. We could use the formula from the BLS signature draft or simply read `2n` bytes where `n` is the width of an encoded field element.

**Comment by BasileiosKal** [comment]
Another option could be `ceil((r+k)/8)` where `k` the security level of the ciphersuite. So for bls would be the same (48 bytes) but for bn462 would be 74 bytes instead of 87 (that it would if we used the `ceil((3 * ceil(log2(r))) / 16)` formula). `2n` will definitely be secure, but it may be too inefficient. It would be 64 bytes for bls and 116 for bn462 if I'm not mistaken.

**Comment by tplooker** [comment]
How about we leave it to the cipher suite to pick the exact value but have the above as a recommended way of calculating it?

**Comment by BasileiosKal** [comment]
+1. Just instead of a recommendation i think we should have `ceil((r+k)/8)` (or `2n` etc) as the minimum value that a ciphersuite must choose though.
